### ISSUE TITLE
19w46b

### ISSUE THREAD

**Issue by Yoghurt4C** [Draylar/mycolor#3]
Description: Rendering screen

java.lang.IllegalAccessError: Class com/github/draylar/cu/client/gui/ColorToggleWidget illegally accessing "private" member of class net/minecraft/class_1060
	at com.github.draylar.cu.client.gui.ColorToggleWidget.render(ColorToggleWidget.java:38)
	at net.minecraft.class_437.render(class_437.java:81)
	at net.minecraft.class_498.render(class_498.java:243)
	at net.minecraft.class_757.method_3192(class_757.java:611)
	at net.minecraft.class_310.method_1523(class_310.java:932)
	at net.minecraft.class_310.method_1514(class_310.java:569)
	at net.minecraft.client.main.Main.main(Main.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.draylar.cu.client.gui.ColorToggleWidget.render(ColorToggleWidget.java:38)
	at net.minecraft.class_437.render(class_437.java:81)
	at net.minecraft.class_498.render(class_498.java:243)

**Comment by Mhowser** [comment]
Same thing for 1.15.1 https://paste.dimdev.org/ubaqumokiv.mccrash

**Comment by Mhowser** [comment]
most recent log with no other mods loaded https://paste.dimdev.org/acibubozoq.mccrash

**Comment by Draylar** [comment]
Fixed in 1.0.2. Thanks!
