### ISSUE TITLE
Crashes when sending messages with a §

### ISSUE THREAD

**Issue by SolidBlock-cn** [Draylar/mycolor#9]
```
---- Minecraft Crash Report ----

// Don't be sad, have a hug! <3

Time: 2020-11-14 11:40:58 CST
Description: Unexpected error

java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.21)
    at com.mamiyaotaru.voxelmap.util.MapChunk.isSurroundedByLoaded(MapChunk.java:83)
    at com.mamiyaotaru.voxelmap.util.MapChunkCache.isChunkSurroundedByLoaded(MapChunkCache.java:142)
    at com.mamiyaotaru.voxelmap.persistent.PersistentMap.isChunkReady(PersistentMap.java:1098)
    at com.mamiyaotaru.voxelmap.persistent.PersistentMap.handleChangeInWorld(PersistentMap.java:1021)
    at com.mamiyaotaru.voxelmap.util.WorldUpdateListener.notifyObservers(WorldUpdateListener.java:47)
    at net.minecraft.client.render.WorldRenderer.handler$zje000$postScheduleChunkRender(WorldRenderer:5718)
    at net.minecraft.client.render.WorldRenderer.scheduleChunkRender(WorldRenderer:2498)
    at net.minecraft.client.render.WorldRenderer.lambdynlights_scheduleChunkRebuild(WorldRenderer)
    at me.lambdaurora.lambdynlights.LambDynLights.scheduleChunkRebuild(LambDynLights.java:414)
    at net.minecraft.entity.Entity.lambdynlights_scheduleTrackedChunksRebuild(Entity:5334)
    at me.lambdaurora.lambdynlights.LambDynLights.clearLightSources(LambDynLights.java:326)
    at net.minecraft.client.MinecraftClient.handler$zkc000$onSetWorld(MinecraftClient:7879)
    at net.minecraft.client.MinecraftClient.setWorld(MinecraftClient)
    at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2025)
    at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:1989)
    at net.minecraft.client.network.ClientPlayNetworkHandler.onDisconnected(ClientPlayNetworkHandler:821)
    at net.minecraft.network.ClientConnection.handleDisconnection(ClientConnection:394)
    at net.minecraft.client.network.ClientPlayerInteractionManager.tick(ClientPlayerInteractionManager:265)
    at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1504)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.MinecraftClient.handler$zfo000$afterCrashHandled(MinecraftClient:4904)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:704)
    at net.minecraft.client.MinecraftClient.handler$zfo000$afterCrashHandled(MinecraftClient:4904)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:704)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_261, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1285509184 bytes (1225 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
  CPUs: 8
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  Suspected Mods: VoxelMap (voxelmap), LambDynamicLights (lambdynlights), Fabric Loader (fabricloader)
  Fabric Mods: cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-config2: Cloth Config v4 4.8.1
               colorunchained: Color Unchained 1.1.1-1.16.4
               customskinloader: CustomSkinLoader 14.13-SNAPSHOT-182
               disablecustomworldsadvice: Disable Custom Worlds Advice 1.1
               fabric: Fabric API 0.25.4+1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c53a
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c593a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
               fabricloader: Fabric Loader 0.10.6+build.214
               imblocker: IMBlockerFabric 1.0.9
               inventoryprofiles: Inventory Profiles 0.4.2
               justmap: Just Map 1.2.16
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               minecraft: Minecraft 1.16.4
               modmenu: Mod Menu 1.14.6+build.31
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               phosphor: Phosphor 0.6.0+build.7
               spruceui: SpruceUI 1.6.4
               tweakeroo: Tweakeroo 0.10.0-dev.20201103.184154
               voxelmap: VoxelMap 1.10.11
               worldedit: WorldEdit 7.2.0+a51fa43
               worldeditcui: WorldEditCUI 1.16.2+01
  Launched Version: HMCL 3.3.170
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce MX250/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.87, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: vanilla, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, fabric/imblocker, fabric/modmenu, fabric/worldedit (incompatible), fabric/worldeditcui, file/More+Canvas+Compat-1.0-1.16.2.zip, fabric/lithium, fabric/voxelmap (incompatible), fabric/cloth-config2, fabric/lambdynlights, fabric/spruceui, file/CPPxHaolongSubway
  Current Language: 简体中文 (中国)
  CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Client Crashes Since Restart: 3
  Integrated Server Crashes Since Restart: 0

```

**Comment by SolidBlock-cn** [comment]
Related to using outdated VoxelMap mod. After removing the Voxel map, the world is exited with a message say illegal chat.
